{application,html_builder,
             [{description,"generate html in elixir with simple data structures"},
              {modules,['Elixir.HTMLBuilder','Elixir.HTMLBuilder.Encoder',
                        'Elixir.HTMLBuilder.Encoder.Atom',
                        'Elixir.HTMLBuilder.Encoder.BitString',
                        'Elixir.HTMLBuilder.Encoder.Float',
                        'Elixir.HTMLBuilder.Encoder.Integer',
                        'Elixir.HTMLBuilder.Encoder.List',
                        'Elixir.HTMLBuilder.Encoder.Tuple',
                        'Elixir.HTMLBuilder.Pretty',
                        'Elixir.HTMLBuilder.Utils']},
              {registered,[]},
              {vsn,"0.1.1"},
              {applications,[kernel,stdlib,elixir,logger]}]}.
