{application,mazurka_plug,
             [{description,"Plug integration for Mazurka"},
              {modules,['Elixir.Mazurka.Conn.Plug.Conn','Elixir.Mazurka.Plug',
                        'Elixir.Mazurka.Plug.Helpers',
                        'Elixir.Mazurka.Plug.Test',
                        'Elixir.Mazurka.Plug.Test.AffordanceProxy',
                        'Elixir.Plug.Exception.Mazurka.ConditionException',
                        'Elixir.Plug.Exception.Mazurka.MissingParametersException',
                        'Elixir.Plug.Exception.Mazurka.MissingRouterException',
                        'Elixir.Plug.Exception.Mazurka.UnacceptableContentTypeException',
                        'Elixir.Plug.Exception.Mazurka.ValidationException']},
              {registered,[]},
              {vsn,"0.1.4"},
              {applications,[kernel,stdlib,elixir,logger]}]}.
