{application,plug_wait1,
             [{description,"Plug adapter for the wait1 protocol"},
              {modules,['Elixir.Plug.Adapters.Wait1',
                        'Elixir.Plug.Adapters.Wait1.Conn',
                        'Elixir.Plug.Adapters.Wait1.Conn.Body',
                        'Elixir.Plug.Adapters.Wait1.Conn.QS',
                        'Elixir.Plug.Adapters.Wait1.Handler',
                        'Elixir.Plug.Adapters.Wait1.Protocol',
                        'Elixir.Plug.Adapters.Wait1.Worker',
                        'Elixir.Plug.Parsers.Wait1',
                        'Elixir.Poison.Encoder.Plug.Adapters.Wait1.Conn.Body',
                        'Elixir.String.Chars.Plug.Adapters.Wait1.Conn.QS']},
              {registered,[]},
              {vsn,"0.2.2"},
              {applications,[kernel,stdlib,elixir,logger]}]}.
